### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by heyadjoining** [beezTEM/TRTLBot#2]
This is a list of commands I thought would be a nice addition and the intended use they would have, given the lack of use of the tradebot for actual trading purposes:

A database would need to be created, or current db modified, adding the following columns:
- Positive rep
- Negative rep
- Rep points
- Completed trades
- Incomplete trades

**Command**: 
`!trade`: To be used only in #turtle-market
**Parameters**: 
`complete/incomplete`: Increments of 1 for the related column.
`@user`: Add the respective values to both the mentioned user and the user using the command (if  applicable)
Optional `(+/-)1-8`: Adds the specified amount of Rep to the pos/neg column. More on this below.

**Command:**
`!rep`: For use in the whole server. Also intended for helping others and getting help.
**Parameters**
`+/-`: Based on the role the user currently has, they get a number of rep points to give every 24 hours.
- Regular users would get 6 points to give a day. 
- Users with the `@trader` role get 10 points a day
- If a user reaches a Positive rep of +50 (or a more calculated number, that just popped in my head), then they get to spend 16 points a day.

`@user`: Sets the specified amount of rep to the pos/neg columns of the user.
`check`: Shows the Rep points the user currently has to give, and the time they will reset.

**Command**
`!info @user`:  it would list:
- Username
- Wallet (optional)
- `pos/neg trades (x% Good/Bad) `: x is calculated like if pos>neg then pos/(pos+neg)+'% Good', else neg/(pos+neg)+'% Bad'.
- `complete/incomplete trades`

There would need to be a cooldown for all of this. Specially the !rep part so it doesn't get abused. 
I was thinking of a way that !trade would delete a listing from !list but couldnt come up with an efficient way without getting rid of permanent offers.
This is expandable and could link to all the current commands in the bot.
Also the points are not well thought out and could use some better approach at calculating them.

Any ideas to efficient all of this are welcome. Thanks!

**Comment by GreatGodApollo** [comment]
So I feel that this will most likely be another table in the DB, so that we can keep trader info separate from trades, I could also make it so that there would be a persistent setting in the `!list` command, and the `!unlist` command only work for the person that made the listing, unlike the current system. The `!trade` command only being used in #turtle-market is a relatively bad idea, it'd be more likely to only be used in the bot channel. The info command I think would sound better as `!trader`, so that it's getting a trader, just an idea. If you have any more ideas, please do expand on this!

**Comment by GreatGodApollo** [comment]
As the bot is not being used anymore all development is halted.
